[libraries]

vunit_lib.files = [
"vunit/vunit/vhdl/check/src/check_api.vhd", 
"vunit/vunit/vhdl/check/src/check_deprecated_pkg.vhd", 
"vunit/vunit/vhdl/check/src/check.vhd", 
"vunit/vunit/vhdl/check/src/checker_pkg-body.vhd", 
"vunit/vunit/vhdl/check/src/checker_pkg.vhd", 
"vunit/vunit/vhdl/com/src/com_api.vhd", 
"vunit/vunit/vhdl/com/src/com_common.vhd", 
"vunit/vunit/vhdl/com/src/com_context.vhd", 
"vunit/vunit/vhdl/com/src/com_debug_codec_builder.vhd", 
"vunit/vunit/vhdl/com/src/com_deprecated.vhd", 
"vunit/vunit/vhdl/com/src/com_messenger.vhd", 
"vunit/vunit/vhdl/com/src/com_string.vhd", 
"vunit/vunit/vhdl/com/src/com_support.vhd", 
"vunit/vunit/vhdl/com/src/com_types.vhd", 
"vunit/vunit/vhdl/com/src/com.vhd", 
"vunit/vunit/vhdl/core/src/core_pkg.vhd", 
"vunit/vunit/vhdl/core/src/stop_body_2008p.vhd", 
"vunit/vunit/vhdl/core/src/stop_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
"vunit/vunit/vhdl/data_types/src/api/external_string_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/codec_builder-2008p.vhd", 
"vunit/vunit/vhdl/data_types/src/codec_builder.vhd", 
"vunit/vunit/vhdl/data_types/src/codec-2008p.vhd", 
"vunit/vunit/vhdl/data_types/src/codec.vhd", 
"vunit/vunit/vhdl/data_types/src/data_types_context.vhd", 
"vunit/vunit/vhdl/data_types/src/data_types_private_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd", 
"vunit/vunit/vhdl/data_types/src/dict_pkg-body.vhd", 
"vunit/vunit/vhdl/data_types/src/dict_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/id_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd", 
"vunit/vunit/vhdl/data_types/src/integer_array_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd", 
"vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd", 
"vunit/vunit/vhdl/data_types/src/queue_pkg-body.vhd", 
"vunit/vunit/vhdl/data_types/src/queue_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/queue_pool_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd", 
"vunit/vunit/vhdl/data_types/src/string_ptr_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd", 
"vunit/vunit/vhdl/data_types/src/types.vhd", 
"vunit/vunit/vhdl/dictionary/src/dictionary.vhd", 
"vunit/vunit/vhdl/logging/src/ansi_pkg.vhd", 
"vunit/vunit/vhdl/logging/src/file_pkg.vhd", 
"vunit/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd", 
"vunit/vunit/vhdl/logging/src/location_pkg.vhd", 
"vunit/vunit/vhdl/logging/src/log_deprecated_pkg.vhd", 
"vunit/vunit/vhdl/logging/src/log_handler_pkg-body.vhd", 
"vunit/vunit/vhdl/logging/src/log_handler_pkg.vhd", 
"vunit/vunit/vhdl/logging/src/log_levels_pkg-body.vhd", 
"vunit/vunit/vhdl/logging/src/log_levels_pkg.vhd", 
"vunit/vunit/vhdl/logging/src/logger_pkg-body.vhd", 
"vunit/vunit/vhdl/logging/src/logger_pkg.vhd", 
"vunit/vunit/vhdl/logging/src/print_pkg-body.vhd", 
"vunit/vunit/vhdl/logging/src/print_pkg.vhd", 
"vunit/vunit/vhdl/path/src/path.vhd", 
"vunit/vunit/vhdl/run/src/run_api.vhd", 
"vunit/vunit/vhdl/run/src/run_deprecated_pkg.vhd", 
"vunit/vunit/vhdl/run/src/run_types.vhd", 
"vunit/vunit/vhdl/run/src/run.vhd", 
"vunit/vunit/vhdl/run/src/runner_pkg.vhd", 
"vunit/vunit/vhdl/string_ops/src/string_ops.vhd", 
"vunit/vunit/vhdl/verification_components/src/avalon_master.vhd", 
"vunit/vunit/vhdl/verification_components/src/avalon_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/avalon_sink.vhd", 
"vunit/vunit/vhdl/verification_components/src/avalon_slave.vhd", 
"vunit/vunit/vhdl/verification_components/src/avalon_source.vhd", 
"vunit/vunit/vhdl/verification_components/src/avalon_stream_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_lite_master_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_lite_master.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_read_slave.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_slave_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_slave_private_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_statistics_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_stream_master.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_stream_monitor.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_stream_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_stream_private_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_stream_protocol_checker.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_stream_slave.vhd", 
"vunit/vunit/vhdl/verification_components/src/axi_write_slave.vhd", 
"vunit/vunit/vhdl/verification_components/src/bus_master_pkg-body.vhd", 
"vunit/vunit/vhdl/verification_components/src/bus_master_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/bus2memory.vhd", 
"vunit/vunit/vhdl/verification_components/src/memory_pkg-body.vhd", 
"vunit/vunit/vhdl/verification_components/src/memory_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/memory_utils_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/ram_master.vhd", 
"vunit/vunit/vhdl/verification_components/src/signal_checker_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/std_logic_checker.vhd", 
"vunit/vunit/vhdl/verification_components/src/stream_master_pkg-body.vhd", 
"vunit/vunit/vhdl/verification_components/src/stream_master_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/stream_slave_pkg-body.vhd", 
"vunit/vunit/vhdl/verification_components/src/stream_slave_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/sync_pkg-body.vhd", 
"vunit/vunit/vhdl/verification_components/src/sync_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/uart_master.vhd", 
"vunit/vunit/vhdl/verification_components/src/uart_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/uart_slave.vhd", 
"vunit/vunit/vhdl/verification_components/src/vc_context.vhd", 
"vunit/vunit/vhdl/verification_components/src/wishbone_master.vhd", 
"vunit/vunit/vhdl/verification_components/src/wishbone_pkg.vhd", 
"vunit/vunit/vhdl/verification_components/src/wishbone_slave.vhd", 
"vunit/vunit/vhdl/vunit_context.vhd", 
"vunit/vunit/vhdl/vunit_run_context.vhd", 
"vunit/vunit/vhdl/random/src/random_pkg.vhd",

# Also add tests
'vunit/vunit/vhdl/run/test/*.vhd',
'vunit/vunit/vhdl/logging/test/*.vhd',
'vunit/vunit/vhdl/string_ops/test/*.vhd',
'vunit/vunit/vhdl/run/test/*.vhd',

'vunit/vunit/vhdl/check/test/tb_checker.vhd',
'vunit/vunit/vhdl/check/test/tb_check_next.vhd',
'vunit/vunit/vhdl/check/test/tb_check_relation_2008p.vhd',
'vunit/vunit/vhdl/check/test/tb_check_stable.vhd',
'vunit/vunit/vhdl/check/test/test_support.vhd',
'vunit/vunit/vhdl/check/test/tb_check_passed.vhd',
'vunit/vunit/vhdl/check/test/tb_check_failed.vhd',
#'vunit/vunit/vhdl/check/test/tb_deprecated.vhd',
'vunit/vunit/vhdl/check/test/tb_check_implication.vhd',
'vunit/vunit/vhdl/check/test/tb_check_sequence.vhd',
'vunit/vunit/vhdl/check/test/tb_check_zero_one_hot.vhd',
'vunit/vunit/vhdl/check/test/tb_check_equal_real.vhd',
'vunit/vunit/vhdl/check/test/tb_check_one_hot.vhd',
'vunit/vunit/vhdl/check/test/tb_result.vhd',
'vunit/vunit/vhdl/check/test/tb_check_not_unknown.vhd',
'vunit/vunit/vhdl/check/test/tb_check_false.vhd',
'vunit/vunit/vhdl/check/test/tb_check_relation.vhd',
'vunit/vunit/vhdl/check/test/tb_check.vhd',

'vunit/vunit/vhdl/verification_components/test/*.vhd',

'vunit/vunit/vhdl/data_types/test/*.vhd',



'vunit/vunit/vhdl/path/test/*.vhd',

'vunit/vunit/vhdl/com/test/constants.vhd',
'vunit/vunit/vhdl/com/test/more_constants.vhd',
#'vunit/vunit/vhdl/com/test/tb_com_codec.vhd',
'vunit/vunit/vhdl/com/test/custom_types.vhd',
'vunit/vunit/vhdl/com/test/tb_com_msg_building.vhd',
'vunit/vunit/vhdl/com/test/tb_com_deprecated.vhd',
'vunit/vunit/vhdl/com/test/tb_com.vhd',

'vunit/vunit/vhdl/dictionary/test/*.vhd',
]

osvvm.files = [
'OSVVM/AlertLogPkg.vhd',
'OSVVM/CoveragePkg.vhd',
'OSVVM/MemoryGenericPkg.vhd',
'OSVVM/MemoryPkg.vhd',
#'OSVVM/MemoryPkg_c.vhd',
#'OSVVM/MemoryPkg_orig_c.vhd',
'OSVVM/MemorySupportPkg.vhd',
'OSVVM/MessageListPkg.vhd',
'OSVVM/MessagePkg.vhd',
'OSVVM/NamePkg.vhd',
'OSVVM/NameStorePkg.vhd',
'OSVVM/OsvvmContext.vhd',
'OSVVM/OsvvmGlobalPkg.vhd',
'OSVVM/OsvvmTypesPkg.vhd',
'OSVVM/RandomBasePkg.vhd',
'OSVVM/RandomPkg.vhd',
'OSVVM/RandomProcedurePkg.vhd',
'OSVVM/ReportPkg.vhd',
'OSVVM/ResizePkg.vhd',
'OSVVM/ResolutionPkg.vhd',
'OSVVM/ScoreboardGenericPkg.vhd',
'OSVVM/ScoreboardPkg_int.vhd',
#'OSVVM/ScoreboardPkg_int_c.vhd',
'OSVVM/ScoreboardPkg_slv.vhd',
#'OSVVM/ScoreboardPkg_slv_c.vhd',
'OSVVM/SortListPkg_int.vhd',
'OSVVM/TbUtilPkg.vhd',
'OSVVM/TextUtilPkg.vhd',
'OSVVM/TranscriptPkg.vhd',
'OSVVM/VendorCovApiPkg.vhd',
#'OSVVM/VendorCovApiPkg_Aldec.vhd',
]

uvvm_util.files = [
'UVVM/uvvm_util/**/*.vhd',
]

uvvm_vvc_framework.files = [
'UVVM/uvvm_vvc_framework/src/*.vhd',
]

bitvis_vip_avalon_mm.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_avalon_mm/**/*.vhd',
]

bitvis_vip_avalon_st.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_avalon_st/**/*.vhd',
]

bitvis_vip_axi.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_axi/**/*.vhd',
]

bitvis_vip_axilite.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_axilite/**/*.vhd',
]

bitvis_vip_axistream.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_axistream/**/*.vhd',
]

bitvis_vip_clock_generator.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_clock_generator/**/*.vhd',
]

bitvis_vip_error_injection.files = [
 'UVVM/bitvis_vip_error_injection/**/*.vhd',
]

bitvis_vip_ethernet.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_ethernet/**/*.vhd',
]

bitvis_vip_gmii.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_gmii/**/*.vhd',
]

bitvis_vip_gpio.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_gpio/**/*.vhd',
]

bitvis_vip_hvvc_to_vvc_bridge.files = [
'UVVM/bitvis_vip_hvvc_to_vvc_bridge/**/*.vhd',
]

bitvis_vip_i2c.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_i2c/**/*.vhd',
]

bitvis_vip_rgmii.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_rgmii/**/*.vhd',
]

bitvis_vip_sbi.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_sbi/**/*.vhd',
]

bitvis_vip_spec_cov.files = [
'UVVM/bitvis_vip_spec_cov/src/*.vhd',
]

bitvis_vip_scoreboard.files = [
'UVVM/bitvis_vip_scoreboard/**/*.vhd',
]

bitvis_vip_spi.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_spi/**/*.vhd',
]

bitvis_vip_uart.files = [
'UVVM/uvvm_vvc_framework/src_target_dependent/*.vhd',
'UVVM/bitvis_vip_uart/**/*.vhd',
]

bitvis_uart.files = [
'UVVM/bitvis_uart/**/*.vhd',
]

bitvis_irqc.files = [
'UVVM/bitvis_irqc/**/*.vhd',
]

PoC.files = [
'PoC/src/sim/sim_global.v08.vhdl',
#'PoC/src/sim/sim_random.v93.vhdl',
#'PoC/src/sim/sim_unprotected.v93.vhdl',
'PoC/src/sim/sim_random.v08.vhdl',
'PoC/src/sim/sim_types.vhdl',
#'PoC/src/sim/sim_global.v93.vhdl',
'PoC/src/sim/sim_VCDParser.vhdl',
'PoC/src/sim/sim_protected.v08.vhdl',
#'PoC/src/sim/sim_simulation.v93.vhdl',
'PoC/src/sim/sim_simulation.v08.vhdl',
'PoC/src/sim/sim_waveform.vhdl',

#'PoC/src/io/iic/*.vhdl',
'PoC/src/io/uart/*.vhdl',

#'PoC/src/io/pmod/*.vhdl',
#'PoC/src/io/*.vhdl',

#'PoC/src/io/ddrio/ddrio_inout_xilinx.vhdl',
'PoC/src/io/ddrio/ddrio_inout.vhdl',
#'PoC/src/io/ddrio/ddrio_inout_altera.vhdl',
'PoC/src/io/ddrio/ddrio_in.vhdl',
'PoC/src/io/ddrio/ddrio.pkg.vhdl',
#'PoC/src/io/ddrio/ddrio_out_altera.vhdl',
#'PoC/src/io/ddrio/ddrio_in_altera.vhdl',
#'PoC/src/io/ddrio/ddrio_out_xilinx.vhdl',
#'PoC/src/io/ddrio/ddrio_in_xilinx.vhdl',
'PoC/src/io/ddrio/ddrio_out.vhdl',

'PoC/src/cache/*.vhdl',

'PoC/src/arith/arith_sqrt.vhdl',
'PoC/src/arith/arith_same.vhdl',
'PoC/src/arith/arith_scaler.vhdl',
'PoC/src/arith/arith_cca.vhdl',
'PoC/src/arith/arith_counter_free.vhdl',
'PoC/src/arith/arith_firstone.vhdl',
#'PoC/src/arith/xilinx/arith_addw_xilinx.vhdl',
#'PoC/src/arith/xilinx/arith_cca_xilinx.vhdl',
#'PoC/src/arith/xilinx/arith_prefix_and_xilinx.vhdl',
#'PoC/src/arith/xilinx/arith_prefix_or_xilinx.vhdl',
#'PoC/src/arith/xilinx/arith_carrychain_inc_xilinx.vhdl',
#'PoC/src/arith/xilinx/arith_inc_ovcy_xilinx.vhdl',
'PoC/src/arith/arith_prefix_or.vhdl',
'PoC/src/arith/arith_carrychain_inc.vhdl',
'PoC/src/arith/arith_addw.vhdl',
'PoC/src/arith/arith_prng.vhdl',
'PoC/src/arith/arith_prefix_and.vhdl',
'PoC/src/arith/arith_convert_bin2bcd.vhdl',
'PoC/src/arith/arith_trng.vhdl',
'PoC/src/arith/arith_shifter_barrel.vhdl',
'PoC/src/arith/arith_counter_bcd.vhdl',
'PoC/src/arith/arith.pkg.vhdl',
'PoC/src/arith/arith_counter_gray.vhdl',
'PoC/src/arith/arith_counter_ring.vhdl',
'PoC/src/arith/arith_div.vhdl',

#'PoC/src/net/arp/*.vhdl',
#'PoC/src/net/udp/*.vhdl',
#'PoC/src/net/ipv4/*.vhdl',
#'PoC/src/net/mac/*.vhdl',
#'PoC/src/net/icmpv4/*.vhdl',
#'PoC/src/net/ipv6/*.vhdl',
#'PoC/src/net/*.vhdl',

#'PoC/src/bus/stream/stream_Source.vhdl',
'PoC/src/bus/stream/stream_DeMux.vhdl',
# Is this file broken, contains undefined types?
#'PoC/src/bus/stream/stream_FrameGenerator.vhdl',
'PoC/src/bus/stream/stream_Mirror.vhdl',
'PoC/src/bus/stream/stream_Mux.vhdl',
# Ambiguous use of to string
#'PoC/src/bus/stream/stream.pkg.vhdl',
'PoC/src/bus/stream/stream_Buffer.vhdl',

'PoC/src/bus/*.vhdl',

'PoC/src/comm/*.vhdl',
#'PoC/src/comm/remote/remote_terminal_control.vhdl',

'PoC/src/common/my_project.vhdl.template',
'PoC/src/common/common.vhdl',
'PoC/src/common/protected.v08.vhdl',
'PoC/src/common/my_config.vhdl.template',
#'PoC/src/common/fileio.v93.vhdl',
'PoC/src/common/fileio.v08.vhdl',
'PoC/src/common/physical.vhdl',
'PoC/src/common/config.vhdl',
'PoC/src/common/vectors.vhdl',
'PoC/src/common/math.vhdl',
'PoC/src/common/strings.vhdl',
'PoC/src/common/debug.vhdl',
'PoC/src/common/components.vhdl',
'PoC/src/common/utils.vhdl',

'PoC/src/sort/sortnet/*.vhdl',
'PoC/src/sort/*.vhdl',
'PoC/src/fifo/fifo.pkg.vhdl',
'PoC/src/fifo/fifo_cc_got.vhdl',
'PoC/src/fifo/fifo_cc_got_tempgot.vhdl',
'PoC/src/fifo/fifo_cc_got_tempput.vhdl',
'PoC/src/fifo/fifo_glue.vhdl',
'PoC/src/fifo/fifo_ic_assembly.vhdl',
'PoC/src/fifo/fifo_shift.vhdl',
'PoC/src/xil/xil.pkg.vhdl',
#'PoC/src/xil/xil_ICAP.vhdl',
#'PoC/src/xil/reconfig/reconfig_icap_wrapper.vhdl',
'PoC/src/xil/reconfig/reconfig_icap_fsm.vhdl',
#'PoC/src/xil/xil_ChipScopeICON.vhdl',
'PoC/src/xil/xil_Reconfigurator.vhdl',
#'PoC/src/xil/xil_BSCAN.vhdl',
#'PoC/src/xil/xil_SystemMonitor.vhdl',

#'PoC/src/mem/sdram/sdram_ctrl_phy_de0.vhdl',
#'PoC/src/mem/sdram/sdram_ctrl_phy_s3esk.vhdl',
#'PoC/src/mem/sdram/sdram_ctrl_de0.vhdl',
#'PoC/src/mem/sdram/sdram_ctrl_s3esk.vhdl',
#'PoC/src/mem/sdram/sdram_ctrl_fsm.vhdl',
#'PoC/src/mem/ddr2/ddr2_mem2mig_adapter_Spartan6.vhdl',
'PoC/src/mem/mem.pkg.vhdl',

'PoC/src/mem/ocram/ocram.pkg.vhdl',
#'PoC/src/mem/ocram/altera/ocram_tdp_altera.vhdl',
#'PoC/src/mem/ocram/altera/ocram_sp_altera.vhdl',
'PoC/src/mem/ocram/ocram_tdp.vhdl',
'PoC/src/mem/ocram/ocram_sdp.vhdl',
'PoC/src/mem/ocram/ocram_sp.vhdl',
'PoC/src/mem/ocram/ocram_tdp_wf.vhdl',
'PoC/src/mem/ocram/ocram_sdp_wf.vhdl',
'PoC/src/mem/ocram/ocram_tdp_sim.vhdl',
'PoC/src/mem/ocram/ocram_esdp.vhdl',

'PoC/src/mem/ddr3/*.vhdl',
'PoC/src/mem/lut/*.vhdl',
'PoC/src/mem/ocrom/*.vhdl',
'PoC/src/misc/stat/*.vhdl',
'PoC/src/misc/filter/*.vhdl',
'PoC/src/misc/gearbox/*.vhdl',

'PoC/src/misc/sync/sync_Vector.vhdl',
#'PoC/src/misc/sync/sync_Reset_Xilinx.vhdl',
#'PoC/src/misc/sync/sync_Bits_Altera.vhdl',
#'PoC/src/misc/sync/sync_Pulse_Xilinx.vhdl',
'PoC/src/misc/sync/sync_Reset.vhdl',
'PoC/src/misc/sync/sync_Strobe.vhdl',
'PoC/src/misc/sync/sync_Bits.vhdl',
#'PoC/src/misc/sync/sync_Reset_Altera.vhdl',
#'PoC/src/misc/sync/sync_Bits_Xilinx.vhdl',
'PoC/src/misc/sync/sync.pkg.vhdl',
'PoC/src/misc/sync/sync_Command.vhdl',
# Missing INIT/INIT_I
#'PoC/src/misc/sync/sync_Pulse_Altera.vhdl',
#'PoC/src/misc/sync/sync_Pulse.vhdl',

'PoC/src/misc/*.vhdl',
'PoC/src/dstruct/*.vhdl',
]

neorv32.files = [
'neorv32/rtl/core/*.vhd',
'neorv32/rtl/core/mem/*default*.vhd',
'neorv32/rtl/processor_templates/*.vhd',
'neorv32/rtl/system_integration/*.vhd',
'neorv32/rtl/test_setups/*.vhd',
'neorv32/sim/*.vhd',
]
