# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2018, Olof Kraigher olof.kraigher@gmail.com

[package]
name = "vhdl_ls"
version = "0.12.0"
authors = ["Olof Kraigher <olof.kraigher@gmail.com>"]
license = "MPL-2.0"
description = "VHDL Language Server"
repository = "https://github.com/kraigher/rust_hdl"
edition = "2018"

[dependencies]
vhdl_parser = { version = "^0", path = "../vhdl_parser"}
jsonrpc-core = "^9"
serde_json = "^1"
serde = "^1"
lsp-types = "^0.63"
fnv = "^1"
log = "0.4.6"
env_logger = "0.6.0"

[dev-dependencies]
tempfile = "^3"
pretty_assertions = "^0"

[features]
default = []
packaged = ["vhdl_parser/packaged"]